#!/bin/bash

# Kindly supply your Github Username and Personal Access Token(without the "ghp_").
usernameMine="<YOUR_GUTHUB_USERNAME>"
tokenMine="<YOUR_PERSONAL_ACCESS_TOKEN>"

yours="$1"
chk="$2"
username="$3"
resp1="$4"
token="$5"
newtok="$6"
num1=36
repo_name="$7"

function exiting ()
{
	echo -e "\nOperation aborted!!!....................."
	exit 1
}

function lines ()
{
	echo ".........................................."
}

echo -e "\nYou are attempting to clone a github repo............\n"
echo -n "Is this repo yours? \"$usernameMine\"? [y] (Anything for NO) >>> "
read yours				#....................1


if [[ "$yours" =~ "y" || "$yours" =~ "Y" ]]; then
	chk="yes"			#....................2
else
	chk="no"			#....................2
fi

echo ""
if [[ "$chk" =~ "no" ]]; then
	echo -n "Pls, provide the github Username (Anything to quit) >>> "
	read username			#....................3

	echo ""
	if [ -z "$username" ]; then
		lines
		echo -e "You must provide a valid Username."
		exiting
	fi

	echo -n "Do you have the PAT(classic) for $username's repo? [y] (Anything for NO) >>> "
	read resp1			#....................4

	echo ""
	if [[ "$resp1" =~ "y" || "$resp1" =~ "Y" ]]; then
		echo -n "Kindly enter the PAT(classic) without the \"ghp_\" >>> "
		read token		#....................5
	
		echo ""
		if [ -z "$token" ]; then
			lines
			echo -e "Didn't you just say you have the PAT?"
			exiting
		fi

		num2=${#token}		#....................6

		#echo "num1 = $num1"
		#echo "num2 = $num2"
		
		if [[ $num2 != $num1 ]]; then
			lines
			echo -e "The token: $token which you supplied is not a classic token.\n"
			echo -e "You've entered a wrong PAT!!!."
			exiting
		fi
	fi
else
	username="$usernameMine"	#....................3
	token="$tokenMine"		#....................4/5
fi

echo -n "Kindly provide the name of the repository >>> "
read repo_name				#....................5/6/7

if [ -z "$repo_name" ]; then
	echo  ""
	lines
	echo -e "You can't clone a repo without a name............"
	exiting
fi

echo -e "\nYou are now cloning the repository \"$repo_name\" in the account \"$username\"....................\n"


if [ -z "$token" ]; then
	git clone https://github.com/$username/$repo_name.git
else
	git clone https://ghp_$token@github.com/$username/$repo_name.git
fi

echo -e "\n....................Tada! All done!....................\n"
echo "This repo \"$repo_name\" has been cloned in this directory: $(pwd)."
lines
echo "NOTE: If you accidentally supplied inaccurate informaion. The repo will NOT be cloned regardless of the successful execution of this program."
lines
