#!/bin/bash

FILE="$1"
SDIR=~/dafCom
OUT="Output file:"

echo ""

if [ "$#" = "0" ]; then
	echo -n "Enter the filename >>> "
	read FILE
fi


echo "....................Creating C file...................."
echo ""
for chk in "$FILE" ; do
	if [[ $chk == *.c ]]; then
		cp "$SDIR/C_template.c" "$FILE"
		echo -e "$OUT $FILE"
	else
		cp "$SDIR/C_template.c" "$FILE.c"
		echo -e "$OUT $FILE.c"
	fi
done

echo ""
echo -e "....................Done...................."


#echo "....................Options...................."
#echo -e "NOTE: these are partial compilations(skip them for complete compilation(Default)\n"
#echo -e "Select [a], [A] or [1] to run through preprocessor and save(text format) without compiling"





#echo ""
#if [[ "$OPTION" =~ "a" || "$OPTION" =~ "A" || "$OPTION" =~ "1" ]]; then
#	echo -e "Preprocessor compilation stage..."
#	echo ""
#	gcc -E $FILE -o preprocessed_$FINNAME
#	echo -e "$OUT preprocessed_$FINNAME"
#fi


