#!/bin/bash

# Kindly supply your Github Username and Personal Access Token(without the "ghp_").
username="<YOUR_GUTHUB_USERNAME>"
token="<YOUR_PERSONAL_ACCESS_TOKEN>"

repo_name="$1"
resp="$2"

if [ -z "$repo_name" ]; then
	echo ""
	echo -n "Please provide a repository name (blank to quit operation) >>> "
	read repo_name

	if [ -z "$repo_name" ]; then
		echo -e "\nYou can't create a repo without a name............"
                echo -e "\nOperation aborted....................."
                exit 1
        fi
fi

echo -e "\nYou are creating the repository \"$repo_name\" in the account \"$username\"....................\n"

if [ -z "$resp" ]; then
	echo -n "Do you wish to proceed? (blank to quit operation) >>> "
	read resp
	
	if [ -z "$resp" ]; then
		echo -e "\nOperation aborted....................."
		exit 1
	fi
fi

git init

curl -u "$username:ghp_$token" -X POST https://api.github.com/user/repos -d '{"name":"'$repo_name'"}'

echo -e "\nPreparing to clone the repo \"$repo_name\" in the directory $(pwd)....................\n"

git clone https://ghp_$token@github.com/$username/$repo_name.git


echo -e "\ncd-ing into the repo \"$repo_name\"....................\n"
cd "$repo_name"

echo -e "\nCreating a default markdown file in $(pwd)................\n"
echo "Repository created" > README.md

echo -e "\nStaging the README file......................."
echo "Committing the creation......................."
echo -e "Pushing the commit to the remote repository.................\n"
git add .
git commit -m "Readme pushed into new repository"
git push

echo -e "\n....................Tada! All done!....................\n"
echo "The repo \"$repo_name\" has been created."
echo "This repo now reside in the github account \"$username\"."
echo "This repo has been cloned in this current directory."
echo "A Default Readme file has also been created, staged and pushed to $username/$repo_name for you."
echo -e ".........................................................\n"
