#!/bin/bash

FILE="$1"
OPTION="$2"
PREFNAME="$3"
OUT="Output file:"

echo ""

if [ "$#" = "0" ]; then
	echo -n "Enter the filename >>> "
	read FILE
fi

#for argument in "$@" ; do
#    echo -e "\n========== $argument =========="
#done

COMP=$(basename $FILE)
NOEXT=${COMP%.*}

echo "....................Options...................."
echo -e "NOTE: these are partial compilations(skip them for complete compilation(Default)\n"
echo -e "Select [a], [A] or [1] to run through preprocessor and save(text format) without compiling"
echo -e "Select [b], [B] or [2] to compile but not link (generates .o file)"
echo -e "Select [c], [C] or [3] to generates the assembly code (.s file)"
echo ""
echo -e "Select [d], [D] or [4] to run normal compilation"
echo -e "Select [e], [E] or [5] to run compilation but turns WARNINGS to ERRORS"
echo -e "Select [f], [F] or [6] to run(Default) c89-standard compilatio but turns WARNINGS to ERRORS"

echo ""
echo -n "Select an option (blank for default compilation) >>> "
read OPTION

echo -n "Enter output name (blank to use filename instead) >>> "
read PREFNAME

echo ""
if [[ -n $PREFNAME ]]; then
	FINNAME=$PREFNAME
else
	FINNAME=$NOEXT
fi

echo ""
echo "....................Compiling...................."

echo ""
if [[ "$OPTION" =~ "a" || "$OPTION" =~ "A" || "$OPTION" =~ "1" ]]; then
	echo -e "Preprocessor compilation stage..."
	echo ""
	gcc -E $FILE -o preprocessed_$FINNAME
	echo -e "$OUT preprocessed_$FINNAME"

elif [[ "$OPTION" =~ "b" || "$OPTION" =~ "B" || "$OPTION" =~ "2" ]]; then
	echo -e "Compilation without linking stage..."
	echo ""
	gcc -c $FILE -o compiled_unlinked_$FINNAME.o
	echo -e "$OUT compiled_unlinked_$FINNAME.o"

elif [[ "$OPTION" =~ "c" || "$OPTION" =~ "C" || "$OPTION" =~ "3" ]]; then
	echo -e "Compilation to assembly stage..."
	echo ""
	gcc -S $FILE -o assembly_$FINNAME.s
	echo -e "$OUT assembly_$FINNAME.s"

elif [[ "$OPTION" =~ "d" || "$OPTION" =~ "D" || "$OPTION" =~ "4" ]]; then
	echo -e "Normal compilation..."
	echo ""
	gcc $FILE -o $FINNAME
	echo -e "$OUT $FINNAME"

elif [[ "$OPTION" =~ "e" || "$OPTION" =~ "E" || "$OPTION" =~ "5" ]]; then
	echo -e "Compilation but turns WARNINGS to ERRORS..."
	echo ""
	gcc -Wall -Werror -Wextra -pedantic $FILE -o $FINNAME
	echo -e "$OUT $FINNAME"

else
	echo -e "Default compilation (c89 standard)..."
	echo ""
	gcc -Wall -Werror -Wextra -pedantic -std=gnu89 $FILE -o $FINNAME
	echo -e "$OUT $FINNAME"
fi

echo ""
echo -e "....................Done...................."

